use_argument_parser: False
data_dir: '/home/lbh/PTINet/data/JAAD/'
dataset: 'jaad'
out_dir: '/home/lbh/PTINet/output/'

input: 5
output: 5
stride: 5
skip: 1 
    # data loading / saving           
dtype: 'train'
from_file: False       
save: True
loader_workers: 8
loader_shuffle: True
pin_memory: True
prefetch_factor: 3
    # training
gpu: 0
device: 'cuda'
batch_size: 8
n_epochs: 50
lr: 0.001
lr_scheduler: False
    # network
hidden_size: 512
hardtanh_limit: 100
use_image: True
image_network: 'clstm'
use_attribute: True
use_opticalflow: True
    # cofe
use_cofe: True
cofe_hidden_size: 96
cofe_num_layers: 2
